import { DollarSign, Users,Eye,ShoppingCart,RotateCcw  } from "lucide-react";
export const stats = [
  {
    title: "Revenue",
    value: "$12,430",
    change: "8.5%",
    trend: "up",
    icon: DollarSign,
    color: "from-green-500 to-emerald-600",
    bgColor: "bg-green-50 dark:bg-green-900/20",
    textColor: "text-green-600 dark:text-green-400",
  },
  {
    title: "New Users",
    value: "1,245",
    change: "4.2%",
    trend: "up",
    icon: Users,
    color: "from-blue-500 to-indigo-600",
    bgColor: "bg-blue-50 dark:bg-blue-900/20",
    textColor: "text-blue-600 dark:text-blue-400",
  },
  {
    title: "Page Views",
    value: "45,892",
    change: "2.1%",
    trend: "down",
    icon: Eye,
    color: "from-orange-500 to-red-600",
    bgColor: "bg-orange-50 dark:bg-orange-900/20",
    textColor: "text-orange-600 dark:text-orange-400",
  },
  {
    title: "Orders",
    value: "983",
    change: "6.3%",
    trend: "up",
    icon: ShoppingCart,
    color: "from-purple-500 to-pink-600",
    bgColor: "bg-purple-50 dark:bg-purple-900/20",
    textColor: "text-purple-600 dark:text-purple-400",
  },
//   {
//     title: "Refunds",
//     value: "32",
//     change: "-1.4%",
//     trend: "down",
//     icon: RotateCcw,
//     color: "from-red-500 to-rose-600",
//     bgColor: "bg-red-50 dark:bg-red-900/20",
//     textColor: "text-red-600 dark:text-red-400",
//   },
];
